# Generated by Django 3.2.3 on 2024-09-07 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240907_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.Ingredient', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не менее 1!')], verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeTag', to='recipes.Tag', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не менее 1!')], verbose_name='теги'),
        ),
    ]
